<?xml version="1.0" encoding="utf-8"?><Database Name="SistemaTutorias" Class="DataClassesTutoriaUVDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.academico" Member="academico">
    <Type Name="academico">
      <Column Name="idacademico" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="numeroempleado" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="correoinstitucional" Type="System.String" DbType="VarChar(45)" CanBeNull="true" />
      <Column Name="correopersonal" Type="System.String" DbType="VarChar(45)" CanBeNull="true" />
      <Column Name="telefono" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="VarChar(45)" CanBeNull="true" />
      <Column Name="roles_idroles" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="academico_estudiante" Member="estudiante" ThisKey="idacademico" OtherKey="idtutor" Type="estudiante" />
      <Association Name="academico_experienciaeducativa" Member="experienciaeducativa" ThisKey="idacademico" OtherKey="idprofesor" Type="experienciaeducativa" />
      <Association Name="academico_programaeducativo" Member="programaeducativo" ThisKey="idacademico" OtherKey="idcoordinador" Type="programaeducativo" />
      <Association Name="academico_programaeducativo1" Member="programaeducativo1" ThisKey="idacademico" OtherKey="idjefecarrera" Type="programaeducativo" />
      <Association Name="academico_reportetutoria" Member="reportetutoria" ThisKey="idacademico" OtherKey="idtutor" Type="reportetutoria" />
      <Association Name="academico_solucionproblematica" Member="solucionproblematica" ThisKey="idacademico" OtherKey="idjefecarrera" Type="solucionproblematica" />
      <Association Name="rol_academico" Member="rol" ThisKey="roles_idroles" OtherKey="idroles" Type="rol" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.estudiante" Member="estudiante">
    <Type Name="estudiante">
      <Column Name="idestudiante" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="matricula" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="correoinstitucional" Type="System.String" DbType="VarChar(45)" CanBeNull="true" />
      <Column Name="correopersonal" Type="System.String" DbType="VarChar(45)" CanBeNull="true" />
      <Column Name="telefono" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="idtutor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idprogramaeducativo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="estudiante_sesion" Member="sesion" ThisKey="idestudiante" OtherKey="idestudiante" Type="sesion" />
      <Association Name="academico_estudiante" Member="academico" ThisKey="idtutor" OtherKey="idacademico" Type="academico" IsForeignKey="true" />
      <Association Name="programaeducativo_estudiante" Member="programaeducativo" ThisKey="idprogramaeducativo" OtherKey="idprogramaeducativo" Type="programaeducativo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.periodoescolar" Member="periodoescolar">
    <Type Name="periodoescolar">
      <Column Name="idperiodoescolar" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="codigo" Type="System.String" DbType="VarChar(45)" CanBeNull="true" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(45)" CanBeNull="true" />
      <Column Name="fechainicio" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="fechafin" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="periodoescolar_experienciaeducativa" Member="experienciaeducativa" ThisKey="idperiodoescolar" OtherKey="idperiodoescolar" Type="experienciaeducativa" />
      <Association Name="periodoescolar_tutoria" Member="tutoria" ThisKey="idperiodoescolar" OtherKey="idperiodoescolar" Type="tutoria" />
    </Type>
  </Table>
  <Table Name="dbo.experienciaeducativa" Member="experienciaeducativa">
    <Type Name="experienciaeducativa">
      <Column Name="idexperienciaeducativa" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NRC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="modalidad" Type="System.String" DbType="VarChar(45)" CanBeNull="true" />
      <Column Name="horario" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="idperiodoescolar" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idprogramaeducativo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idprofesor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="periodoescolar_experienciaeducativa" Member="periodoescolar" ThisKey="idperiodoescolar" OtherKey="idperiodoescolar" Type="periodoescolar" IsForeignKey="true" />
      <Association Name="academico_experienciaeducativa" Member="academico" ThisKey="idprofesor" OtherKey="idacademico" Type="academico" IsForeignKey="true" />
      <Association Name="programaeducativo_experienciaeducativa" Member="programaeducativo" ThisKey="idprogramaeducativo" OtherKey="idprogramaeducativo" Type="programaeducativo" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.problematica" Member="problematica">
    <Type Name="problematica">
      <Column Name="idproblematica" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(45)" CanBeNull="true" />
      <Column Name="tipo" Type="System.String" DbType="VarChar(45)" CanBeNull="true" />
      <Association Name="problematica_problematicasesion" Member="problematicasesion" ThisKey="idproblematica" OtherKey="idproblematica" Type="problematicasesion" />
    </Type>
  </Table>
  <Table Name="dbo.problematicasesion" Member="problematicasesion">
    <Type Name="problematicasesion">
      <Column Name="idproblematicasesion" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="estado" Type="System.String" DbType="VarChar(45)" CanBeNull="true" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="experienciaeducativa" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="idproblematica" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idsesion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="problematicasesion_solucionproblematica" Member="solucionproblematica" ThisKey="idproblematicasesion" OtherKey="idproblematicasesion" Type="solucionproblematica" />
      <Association Name="problematica_problematicasesion" Member="problematica" ThisKey="idproblematica" OtherKey="idproblematica" Type="problematica" IsForeignKey="true" />
      <Association Name="sesion_problematicasesion" Member="sesion" ThisKey="idsesion" OtherKey="idsesion" Type="sesion" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.programaeducativo" Member="programaeducativo">
    <Type Name="programaeducativo">
      <Column Name="idprogramaeducativo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="codigo" Type="System.String" DbType="VarChar(45)" CanBeNull="true" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(45)" CanBeNull="true" />
      <Column Name="idcoordinador" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idjefecarrera" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="programaeducativo_estudiante" Member="estudiante" ThisKey="idprogramaeducativo" OtherKey="idprogramaeducativo" Type="estudiante" />
      <Association Name="programaeducativo_experienciaeducativa" Member="experienciaeducativa" ThisKey="idprogramaeducativo" OtherKey="idprogramaeducativo" Type="experienciaeducativa" />
      <Association Name="programaeducativo_reportetutoria" Member="reportetutoria" ThisKey="idprogramaeducativo" OtherKey="programaeducativo_idprogramaeducativo" Type="reportetutoria" />
      <Association Name="academico_programaeducativo" Member="academico" ThisKey="idcoordinador" OtherKey="idacademico" Type="academico" IsForeignKey="true" />
      <Association Name="academico_programaeducativo1" Member="academico1" ThisKey="idjefecarrera" OtherKey="idacademico" Type="academico" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.reportegeneral" Member="reportegeneral">
    <Type Name="reportegeneral">
      <Column Name="idreportegeneral" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="porcentajeasistencia" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="porcentajeriesgo" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="reportegeneral_reportegeneral_has_reportetutoria" Member="reportegeneral_has_reportetutoria" ThisKey="idreportegeneral" OtherKey="reportegeneral_idreportegeneral" Type="reportegeneral_has_reportetutoria" />
    </Type>
  </Table>
  <Table Name="dbo.reportetutoria" Member="reportetutoria">
    <Type Name="reportetutoria">
      <Column Name="idreportetutoria" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="porcentajeasistencia" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="porcentajeriesgo" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="comentariosgenerales" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="fechacreacion" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="idtutoria" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="programaeducativo_idprogramaeducativo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idtutor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="reportetutoria_reportegeneral_has_reportetutoria" Member="reportegeneral_has_reportetutoria" ThisKey="idreportetutoria" OtherKey="reporteetutoria_idreportetutoria" Type="reportegeneral_has_reportetutoria" />
      <Association Name="programaeducativo_reportetutoria" Member="programaeducativo" ThisKey="programaeducativo_idprogramaeducativo" OtherKey="idprogramaeducativo" Type="programaeducativo" IsForeignKey="true" />
      <Association Name="academico_reportetutoria" Member="academico" ThisKey="idtutor" OtherKey="idacademico" Type="academico" IsForeignKey="true" />
      <Association Name="tutoria_reportetutoria" Member="tutoria" ThisKey="idtutoria" OtherKey="idtutoria" Type="tutoria" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.reportegeneral_has_reportetutoria" Member="reportegeneral_has_reportetutoria">
    <Type Name="reportegeneral_has_reportetutoria">
      <Column Name="reportegeneral_idreportegeneral" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="reporteetutoria_idreportetutoria" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="reportegeneral_reportegeneral_has_reportetutoria" Member="reportegeneral" ThisKey="reportegeneral_idreportegeneral" OtherKey="idreportegeneral" Type="reportegeneral" IsForeignKey="true" />
      <Association Name="reportetutoria_reportegeneral_has_reportetutoria" Member="reportetutoria" ThisKey="reporteetutoria_idreportetutoria" OtherKey="idreportetutoria" Type="reportetutoria" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.rol" Member="rol">
    <Type Name="rol">
      <Column Name="idroles" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="rol" Member="rol1" Type="System.String" DbType="VarChar(45)" CanBeNull="true" />
      <Association Name="rol_academico" Member="academico" ThisKey="idroles" OtherKey="roles_idroles" Type="academico" />
    </Type>
  </Table>
  <Table Name="dbo.sesion" Member="sesion">
    <Type Name="sesion">
      <Column Name="idsesion" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idestudiante" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idtutoria" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="horario" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="lugar" Type="System.String" DbType="VarChar(45)" CanBeNull="true" />
      <Column Name="asistencia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="riesgo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="observaciones" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="sesion_problematicasesion" Member="problematicasesion" ThisKey="idsesion" OtherKey="idsesion" Type="problematicasesion" />
      <Association Name="estudiante_sesion" Member="estudiante" ThisKey="idestudiante" OtherKey="idestudiante" Type="estudiante" IsForeignKey="true" />
      <Association Name="tutoria_sesion" Member="tutoria" ThisKey="idtutoria" OtherKey="idtutoria" Type="tutoria" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.solucionproblematica" Member="solucionproblematica">
    <Type Name="solucionproblematica">
      <Column Name="idsolucionproblematica" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="titulo" Type="System.String" DbType="VarChar(45)" CanBeNull="true" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(45)" CanBeNull="true" />
      <Column Name="idjefecarrera" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="idproblematicasesion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="academico_solucionproblematica" Member="academico" ThisKey="idjefecarrera" OtherKey="idacademico" Type="academico" IsForeignKey="true" />
      <Association Name="problematicasesion_solucionproblematica" Member="problematicasesion" ThisKey="idproblematicasesion" OtherKey="idproblematicasesion" Type="problematicasesion" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tutoria" Member="tutoria">
    <Type Name="tutoria">
      <Column Name="idtutoria" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="numerosesion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fechasesion" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="numerodias" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fechacierre" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="idperiodoescolar" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tutoria_reportetutoria" Member="reportetutoria" ThisKey="idtutoria" OtherKey="idtutoria" Type="reportetutoria" />
      <Association Name="tutoria_sesion" Member="sesion" ThisKey="idtutoria" OtherKey="idtutoria" Type="sesion" />
      <Association Name="periodoescolar_tutoria" Member="periodoescolar" ThisKey="idperiodoescolar" OtherKey="idperiodoescolar" Type="periodoescolar" IsForeignKey="true" />
    </Type>
  </Table>
</Database>