//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="academico", Namespace="http://schemas.datacontract.org/2004/07/WCFSistemaTutorias")]
    public partial class academico : object
    {
        
        private string correoinstitucionalField;
        
        private string correopersonalField;
        
        private ServiceReference1.estudiante[] estudianteField;
        
        private ServiceReference1.experienciaeducativa[] experienciaeducativaField;
        
        private int idacademicoField;
        
        private string nombreField;
        
        private System.Nullable<int> numeroempleadoField;
        
        private string passwordField;
        
        private ServiceReference1.programaeducativo[] programaeducativoField;
        
        private ServiceReference1.programaeducativo[] programaeducativo1Field;
        
        private ServiceReference1.reportetutoria[] reportetutoriaField;
        
        private ServiceReference1.rol rolField;
        
        private System.Nullable<int> roles_idrolesField;
        
        private ServiceReference1.solucionproblematica[] solucionproblematicaField;
        
        private string telefonoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string correoinstitucional
        {
            get
            {
                return this.correoinstitucionalField;
            }
            set
            {
                this.correoinstitucionalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string correopersonal
        {
            get
            {
                return this.correopersonalField;
            }
            set
            {
                this.correopersonalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.estudiante[] estudiante
        {
            get
            {
                return this.estudianteField;
            }
            set
            {
                this.estudianteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.experienciaeducativa[] experienciaeducativa
        {
            get
            {
                return this.experienciaeducativaField;
            }
            set
            {
                this.experienciaeducativaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idacademico
        {
            get
            {
                return this.idacademicoField;
            }
            set
            {
                this.idacademicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> numeroempleado
        {
            get
            {
                return this.numeroempleadoField;
            }
            set
            {
                this.numeroempleadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.programaeducativo[] programaeducativo
        {
            get
            {
                return this.programaeducativoField;
            }
            set
            {
                this.programaeducativoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.programaeducativo[] programaeducativo1
        {
            get
            {
                return this.programaeducativo1Field;
            }
            set
            {
                this.programaeducativo1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.reportetutoria[] reportetutoria
        {
            get
            {
                return this.reportetutoriaField;
            }
            set
            {
                this.reportetutoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.rol rol
        {
            get
            {
                return this.rolField;
            }
            set
            {
                this.rolField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> roles_idroles
        {
            get
            {
                return this.roles_idrolesField;
            }
            set
            {
                this.roles_idrolesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.solucionproblematica[] solucionproblematica
        {
            get
            {
                return this.solucionproblematicaField;
            }
            set
            {
                this.solucionproblematicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string telefono
        {
            get
            {
                return this.telefonoField;
            }
            set
            {
                this.telefonoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="rol", Namespace="http://schemas.datacontract.org/2004/07/WCFSistemaTutorias")]
    public partial class rol : object
    {
        
        private ServiceReference1.academico[] academicoField;
        
        private int idrolesField;
        
        private string rol1Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.academico[] academico
        {
            get
            {
                return this.academicoField;
            }
            set
            {
                this.academicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idroles
        {
            get
            {
                return this.idrolesField;
            }
            set
            {
                this.idrolesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rol1
        {
            get
            {
                return this.rol1Field;
            }
            set
            {
                this.rol1Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="estudiante", Namespace="http://schemas.datacontract.org/2004/07/WCFSistemaTutorias")]
    public partial class estudiante : object
    {
        
        private ServiceReference1.academico academicoField;
        
        private string correoinstitucionalField;
        
        private string correopersonalField;
        
        private int idestudianteField;
        
        private System.Nullable<int> idprogramaeducativoField;
        
        private System.Nullable<int> idtutorField;
        
        private string matriculaField;
        
        private string nombreField;
        
        private ServiceReference1.programaeducativo programaeducativoField;
        
        private ServiceReference1.sesion[] sesionField;
        
        private string telefonoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.academico academico
        {
            get
            {
                return this.academicoField;
            }
            set
            {
                this.academicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string correoinstitucional
        {
            get
            {
                return this.correoinstitucionalField;
            }
            set
            {
                this.correoinstitucionalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string correopersonal
        {
            get
            {
                return this.correopersonalField;
            }
            set
            {
                this.correopersonalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idestudiante
        {
            get
            {
                return this.idestudianteField;
            }
            set
            {
                this.idestudianteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idprogramaeducativo
        {
            get
            {
                return this.idprogramaeducativoField;
            }
            set
            {
                this.idprogramaeducativoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idtutor
        {
            get
            {
                return this.idtutorField;
            }
            set
            {
                this.idtutorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string matricula
        {
            get
            {
                return this.matriculaField;
            }
            set
            {
                this.matriculaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.programaeducativo programaeducativo
        {
            get
            {
                return this.programaeducativoField;
            }
            set
            {
                this.programaeducativoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.sesion[] sesion
        {
            get
            {
                return this.sesionField;
            }
            set
            {
                this.sesionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string telefono
        {
            get
            {
                return this.telefonoField;
            }
            set
            {
                this.telefonoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="experienciaeducativa", Namespace="http://schemas.datacontract.org/2004/07/WCFSistemaTutorias")]
    public partial class experienciaeducativa : object
    {
        
        private System.Nullable<int> NRCField;
        
        private ServiceReference1.academico academicoField;
        
        private string horarioField;
        
        private int idexperienciaeducativaField;
        
        private System.Nullable<int> idperiodoescolarField;
        
        private System.Nullable<int> idprofesorField;
        
        private System.Nullable<int> idprogramaeducativoField;
        
        private string modalidadField;
        
        private string nombreField;
        
        private ServiceReference1.periodoescolar periodoescolarField;
        
        private ServiceReference1.programaeducativo programaeducativoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NRC
        {
            get
            {
                return this.NRCField;
            }
            set
            {
                this.NRCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.academico academico
        {
            get
            {
                return this.academicoField;
            }
            set
            {
                this.academicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string horario
        {
            get
            {
                return this.horarioField;
            }
            set
            {
                this.horarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idexperienciaeducativa
        {
            get
            {
                return this.idexperienciaeducativaField;
            }
            set
            {
                this.idexperienciaeducativaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idperiodoescolar
        {
            get
            {
                return this.idperiodoescolarField;
            }
            set
            {
                this.idperiodoescolarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idprofesor
        {
            get
            {
                return this.idprofesorField;
            }
            set
            {
                this.idprofesorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idprogramaeducativo
        {
            get
            {
                return this.idprogramaeducativoField;
            }
            set
            {
                this.idprogramaeducativoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string modalidad
        {
            get
            {
                return this.modalidadField;
            }
            set
            {
                this.modalidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.periodoescolar periodoescolar
        {
            get
            {
                return this.periodoescolarField;
            }
            set
            {
                this.periodoescolarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.programaeducativo programaeducativo
        {
            get
            {
                return this.programaeducativoField;
            }
            set
            {
                this.programaeducativoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="programaeducativo", Namespace="http://schemas.datacontract.org/2004/07/WCFSistemaTutorias")]
    public partial class programaeducativo : object
    {
        
        private ServiceReference1.academico academicoField;
        
        private ServiceReference1.academico academico1Field;
        
        private string codigoField;
        
        private ServiceReference1.estudiante[] estudianteField;
        
        private ServiceReference1.experienciaeducativa[] experienciaeducativaField;
        
        private System.Nullable<int> idcoordinadorField;
        
        private System.Nullable<int> idjefecarreraField;
        
        private int idprogramaeducativoField;
        
        private string nombreField;
        
        private ServiceReference1.reportetutoria[] reportetutoriaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.academico academico
        {
            get
            {
                return this.academicoField;
            }
            set
            {
                this.academicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.academico academico1
        {
            get
            {
                return this.academico1Field;
            }
            set
            {
                this.academico1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.estudiante[] estudiante
        {
            get
            {
                return this.estudianteField;
            }
            set
            {
                this.estudianteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.experienciaeducativa[] experienciaeducativa
        {
            get
            {
                return this.experienciaeducativaField;
            }
            set
            {
                this.experienciaeducativaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idcoordinador
        {
            get
            {
                return this.idcoordinadorField;
            }
            set
            {
                this.idcoordinadorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idjefecarrera
        {
            get
            {
                return this.idjefecarreraField;
            }
            set
            {
                this.idjefecarreraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idprogramaeducativo
        {
            get
            {
                return this.idprogramaeducativoField;
            }
            set
            {
                this.idprogramaeducativoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.reportetutoria[] reportetutoria
        {
            get
            {
                return this.reportetutoriaField;
            }
            set
            {
                this.reportetutoriaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="reportetutoria", Namespace="http://schemas.datacontract.org/2004/07/WCFSistemaTutorias")]
    public partial class reportetutoria : object
    {
        
        private ServiceReference1.academico academicoField;
        
        private string comentariosgeneralesField;
        
        private System.Nullable<System.DateTime> fechacreacionField;
        
        private int idreportetutoriaField;
        
        private System.Nullable<int> idtutorField;
        
        private System.Nullable<int> idtutoriaField;
        
        private System.Nullable<double> porcentajeasistenciaField;
        
        private System.Nullable<double> porcentajeriesgoField;
        
        private ServiceReference1.programaeducativo programaeducativoField;
        
        private System.Nullable<int> programaeducativo_idprogramaeducativoField;
        
        private ServiceReference1.reportegeneral_has_reportetutoria[] reportegeneral_has_reportetutoriaField;
        
        private ServiceReference1.tutoria tutoriaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.academico academico
        {
            get
            {
                return this.academicoField;
            }
            set
            {
                this.academicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string comentariosgenerales
        {
            get
            {
                return this.comentariosgeneralesField;
            }
            set
            {
                this.comentariosgeneralesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> fechacreacion
        {
            get
            {
                return this.fechacreacionField;
            }
            set
            {
                this.fechacreacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idreportetutoria
        {
            get
            {
                return this.idreportetutoriaField;
            }
            set
            {
                this.idreportetutoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idtutor
        {
            get
            {
                return this.idtutorField;
            }
            set
            {
                this.idtutorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idtutoria
        {
            get
            {
                return this.idtutoriaField;
            }
            set
            {
                this.idtutoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> porcentajeasistencia
        {
            get
            {
                return this.porcentajeasistenciaField;
            }
            set
            {
                this.porcentajeasistenciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> porcentajeriesgo
        {
            get
            {
                return this.porcentajeriesgoField;
            }
            set
            {
                this.porcentajeriesgoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.programaeducativo programaeducativo
        {
            get
            {
                return this.programaeducativoField;
            }
            set
            {
                this.programaeducativoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> programaeducativo_idprogramaeducativo
        {
            get
            {
                return this.programaeducativo_idprogramaeducativoField;
            }
            set
            {
                this.programaeducativo_idprogramaeducativoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.reportegeneral_has_reportetutoria[] reportegeneral_has_reportetutoria
        {
            get
            {
                return this.reportegeneral_has_reportetutoriaField;
            }
            set
            {
                this.reportegeneral_has_reportetutoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.tutoria tutoria
        {
            get
            {
                return this.tutoriaField;
            }
            set
            {
                this.tutoriaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="solucionproblematica", Namespace="http://schemas.datacontract.org/2004/07/WCFSistemaTutorias")]
    public partial class solucionproblematica : object
    {
        
        private ServiceReference1.academico academicoField;
        
        private string descripcionField;
        
        private System.Nullable<int> idjefecarreraField;
        
        private System.Nullable<int> idproblematicasesionField;
        
        private int idsolucionproblematicaField;
        
        private ServiceReference1.problematicasesion problematicasesionField;
        
        private string tituloField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.academico academico
        {
            get
            {
                return this.academicoField;
            }
            set
            {
                this.academicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idjefecarrera
        {
            get
            {
                return this.idjefecarreraField;
            }
            set
            {
                this.idjefecarreraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idproblematicasesion
        {
            get
            {
                return this.idproblematicasesionField;
            }
            set
            {
                this.idproblematicasesionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idsolucionproblematica
        {
            get
            {
                return this.idsolucionproblematicaField;
            }
            set
            {
                this.idsolucionproblematicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.problematicasesion problematicasesion
        {
            get
            {
                return this.problematicasesionField;
            }
            set
            {
                this.problematicasesionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string titulo
        {
            get
            {
                return this.tituloField;
            }
            set
            {
                this.tituloField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="sesion", Namespace="http://schemas.datacontract.org/2004/07/WCFSistemaTutorias")]
    public partial class sesion : object
    {
        
        private System.Nullable<int> asistenciaField;
        
        private ServiceReference1.estudiante estudianteField;
        
        private string horarioField;
        
        private System.Nullable<int> idestudianteField;
        
        private int idsesionField;
        
        private System.Nullable<int> idtutoriaField;
        
        private string lugarField;
        
        private string observacionesField;
        
        private ServiceReference1.problematicasesion[] problematicasesionField;
        
        private System.Nullable<int> riesgoField;
        
        private ServiceReference1.tutoria tutoriaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> asistencia
        {
            get
            {
                return this.asistenciaField;
            }
            set
            {
                this.asistenciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.estudiante estudiante
        {
            get
            {
                return this.estudianteField;
            }
            set
            {
                this.estudianteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string horario
        {
            get
            {
                return this.horarioField;
            }
            set
            {
                this.horarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idestudiante
        {
            get
            {
                return this.idestudianteField;
            }
            set
            {
                this.idestudianteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idsesion
        {
            get
            {
                return this.idsesionField;
            }
            set
            {
                this.idsesionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idtutoria
        {
            get
            {
                return this.idtutoriaField;
            }
            set
            {
                this.idtutoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lugar
        {
            get
            {
                return this.lugarField;
            }
            set
            {
                this.lugarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string observaciones
        {
            get
            {
                return this.observacionesField;
            }
            set
            {
                this.observacionesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.problematicasesion[] problematicasesion
        {
            get
            {
                return this.problematicasesionField;
            }
            set
            {
                this.problematicasesionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> riesgo
        {
            get
            {
                return this.riesgoField;
            }
            set
            {
                this.riesgoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.tutoria tutoria
        {
            get
            {
                return this.tutoriaField;
            }
            set
            {
                this.tutoriaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="periodoescolar", Namespace="http://schemas.datacontract.org/2004/07/WCFSistemaTutorias")]
    public partial class periodoescolar : object
    {
        
        private string codigoField;
        
        private ServiceReference1.experienciaeducativa[] experienciaeducativaField;
        
        private System.Nullable<System.DateTime> fechafinField;
        
        private System.Nullable<System.DateTime> fechainicioField;
        
        private int idperiodoescolarField;
        
        private string nombreField;
        
        private ServiceReference1.tutoria[] tutoriaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.experienciaeducativa[] experienciaeducativa
        {
            get
            {
                return this.experienciaeducativaField;
            }
            set
            {
                this.experienciaeducativaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> fechafin
        {
            get
            {
                return this.fechafinField;
            }
            set
            {
                this.fechafinField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> fechainicio
        {
            get
            {
                return this.fechainicioField;
            }
            set
            {
                this.fechainicioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idperiodoescolar
        {
            get
            {
                return this.idperiodoescolarField;
            }
            set
            {
                this.idperiodoescolarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.tutoria[] tutoria
        {
            get
            {
                return this.tutoriaField;
            }
            set
            {
                this.tutoriaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tutoria", Namespace="http://schemas.datacontract.org/2004/07/WCFSistemaTutorias")]
    public partial class tutoria : object
    {
        
        private System.Nullable<System.DateTime> fechacierreField;
        
        private System.Nullable<System.DateTime> fechasesionField;
        
        private System.Nullable<int> idperiodoescolarField;
        
        private int idtutoriaField;
        
        private System.Nullable<int> numerodiasField;
        
        private System.Nullable<int> numerosesionField;
        
        private ServiceReference1.periodoescolar periodoescolarField;
        
        private ServiceReference1.reportetutoria[] reportetutoriaField;
        
        private ServiceReference1.sesion[] sesionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> fechacierre
        {
            get
            {
                return this.fechacierreField;
            }
            set
            {
                this.fechacierreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> fechasesion
        {
            get
            {
                return this.fechasesionField;
            }
            set
            {
                this.fechasesionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idperiodoescolar
        {
            get
            {
                return this.idperiodoescolarField;
            }
            set
            {
                this.idperiodoescolarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idtutoria
        {
            get
            {
                return this.idtutoriaField;
            }
            set
            {
                this.idtutoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> numerodias
        {
            get
            {
                return this.numerodiasField;
            }
            set
            {
                this.numerodiasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> numerosesion
        {
            get
            {
                return this.numerosesionField;
            }
            set
            {
                this.numerosesionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.periodoescolar periodoescolar
        {
            get
            {
                return this.periodoescolarField;
            }
            set
            {
                this.periodoescolarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.reportetutoria[] reportetutoria
        {
            get
            {
                return this.reportetutoriaField;
            }
            set
            {
                this.reportetutoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.sesion[] sesion
        {
            get
            {
                return this.sesionField;
            }
            set
            {
                this.sesionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="reportegeneral_has_reportetutoria", Namespace="http://schemas.datacontract.org/2004/07/WCFSistemaTutorias")]
    public partial class reportegeneral_has_reportetutoria : object
    {
        
        private int reporteetutoria_idreportetutoriaField;
        
        private ServiceReference1.reportegeneral reportegeneralField;
        
        private int reportegeneral_idreportegeneralField;
        
        private ServiceReference1.reportetutoria reportetutoriaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int reporteetutoria_idreportetutoria
        {
            get
            {
                return this.reporteetutoria_idreportetutoriaField;
            }
            set
            {
                this.reporteetutoria_idreportetutoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.reportegeneral reportegeneral
        {
            get
            {
                return this.reportegeneralField;
            }
            set
            {
                this.reportegeneralField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int reportegeneral_idreportegeneral
        {
            get
            {
                return this.reportegeneral_idreportegeneralField;
            }
            set
            {
                this.reportegeneral_idreportegeneralField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.reportetutoria reportetutoria
        {
            get
            {
                return this.reportetutoriaField;
            }
            set
            {
                this.reportetutoriaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="reportegeneral", Namespace="http://schemas.datacontract.org/2004/07/WCFSistemaTutorias")]
    public partial class reportegeneral : object
    {
        
        private int idreportegeneralField;
        
        private System.Nullable<double> porcentajeasistenciaField;
        
        private System.Nullable<double> porcentajeriesgoField;
        
        private ServiceReference1.reportegeneral_has_reportetutoria[] reportegeneral_has_reportetutoriaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idreportegeneral
        {
            get
            {
                return this.idreportegeneralField;
            }
            set
            {
                this.idreportegeneralField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> porcentajeasistencia
        {
            get
            {
                return this.porcentajeasistenciaField;
            }
            set
            {
                this.porcentajeasistenciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> porcentajeriesgo
        {
            get
            {
                return this.porcentajeriesgoField;
            }
            set
            {
                this.porcentajeriesgoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.reportegeneral_has_reportetutoria[] reportegeneral_has_reportetutoria
        {
            get
            {
                return this.reportegeneral_has_reportetutoriaField;
            }
            set
            {
                this.reportegeneral_has_reportetutoriaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="problematicasesion", Namespace="http://schemas.datacontract.org/2004/07/WCFSistemaTutorias")]
    public partial class problematicasesion : object
    {
        
        private string descripcionField;
        
        private string estadoField;
        
        private string experienciaeducativaField;
        
        private System.Nullable<int> idproblematicaField;
        
        private int idproblematicasesionField;
        
        private System.Nullable<int> idsesionField;
        
        private ServiceReference1.problematica problematicaField;
        
        private ServiceReference1.sesion sesionField;
        
        private ServiceReference1.solucionproblematica[] solucionproblematicaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string experienciaeducativa
        {
            get
            {
                return this.experienciaeducativaField;
            }
            set
            {
                this.experienciaeducativaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idproblematica
        {
            get
            {
                return this.idproblematicaField;
            }
            set
            {
                this.idproblematicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idproblematicasesion
        {
            get
            {
                return this.idproblematicasesionField;
            }
            set
            {
                this.idproblematicasesionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idsesion
        {
            get
            {
                return this.idsesionField;
            }
            set
            {
                this.idsesionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.problematica problematica
        {
            get
            {
                return this.problematicaField;
            }
            set
            {
                this.problematicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.sesion sesion
        {
            get
            {
                return this.sesionField;
            }
            set
            {
                this.sesionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.solucionproblematica[] solucionproblematica
        {
            get
            {
                return this.solucionproblematicaField;
            }
            set
            {
                this.solucionproblematicaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="problematica", Namespace="http://schemas.datacontract.org/2004/07/WCFSistemaTutorias")]
    public partial class problematica : object
    {
        
        private int idproblematicaField;
        
        private string nombreField;
        
        private ServiceReference1.problematicasesion[] problematicasesionField;
        
        private string tipoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idproblematica
        {
            get
            {
                return this.idproblematicaField;
            }
            set
            {
                this.idproblematicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.problematicasesion[] problematicasesion
        {
            get
            {
                return this.problematicasesionField;
            }
            set
            {
                this.problematicasesionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tipo
        {
            get
            {
                return this.tipoField;
            }
            set
            {
                this.tipoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/IniciarSesion", ReplyAction="http://tempuri.org/IService1/IniciarSesionResponse")]
        System.Threading.Tasks.Task<ServiceReference1.academico> IniciarSesionAsync(int numeroEmpleado, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EsTutor", ReplyAction="http://tempuri.org/IService1/EsTutorResponse")]
        System.Threading.Tasks.Task<bool> EsTutorAsync(int numeroEmpleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EsJefeCarrera", ReplyAction="http://tempuri.org/IService1/EsJefeCarreraResponse")]
        System.Threading.Tasks.Task<bool> EsJefeCarreraAsync(int numeroEmpleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EsCoordinador", ReplyAction="http://tempuri.org/IService1/EsCoordinadorResponse")]
        System.Threading.Tasks.Task<bool> EsCoordinadorAsync(int numeroEmpleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RecuperarEstudiantesSesion", ReplyAction="http://tempuri.org/IService1/RecuperarEstudiantesSesionResponse")]
        System.Threading.Tasks.Task<ServiceReference1.estudiante[]> RecuperarEstudiantesSesionAsync(int idTutor, int numeroSesion, string periodoEscolar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegistrarReporteSesion", ReplyAction="http://tempuri.org/IService1/RegistrarReporteSesionResponse")]
        System.Threading.Tasks.Task<bool> RegistrarReporteSesionAsync(ServiceReference1.sesion Sesion, string nombre, string periodo, int numeroSesion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RecuperarIdSesion", ReplyAction="http://tempuri.org/IService1/RecuperarIdSesionResponse")]
        System.Threading.Tasks.Task<int> RecuperarIdSesionAsync(string periodo, int numeroSesion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CalcularPorcentajesReporte", ReplyAction="http://tempuri.org/IService1/CalcularPorcentajesReporteResponse")]
        System.Threading.Tasks.Task<ServiceReference1.reportetutoria> CalcularPorcentajesReporteAsync(int idTutoria, int idTutor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegistrarPorcentajesReporte", ReplyAction="http://tempuri.org/IService1/RegistrarPorcentajesReporteResponse")]
        System.Threading.Tasks.Task<bool> RegistrarPorcentajesReporteAsync(int idtutoria, int idtutor, double porcentajeriesgo, double porcentajeasistencia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegistrarComentariosGenerales", ReplyAction="http://tempuri.org/IService1/RegistrarComentariosGeneralesResponse")]
        System.Threading.Tasks.Task<bool> RegistrarComentariosGeneralesAsync(int idTutoria, int idTutor, string comentariosGenerales);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RecuperarInformacionExperienciasEducativas", ReplyAction="http://tempuri.org/IService1/RecuperarInformacionExperienciasEducativasResponse")]
        System.Threading.Tasks.Task<string[]> RecuperarInformacionExperienciasEducativasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegistrarProblematica", ReplyAction="http://tempuri.org/IService1/RegistrarProblematicaResponse")]
        System.Threading.Tasks.Task<int> RegistrarProblematicaAsync(string tipo, string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegistrarProblematicaSesion", ReplyAction="http://tempuri.org/IService1/RegistrarProblematicaSesionResponse")]
        System.Threading.Tasks.Task<bool> RegistrarProblematicaSesionAsync(int idProblematica, int idSesion, string descripcion, string experienciaEducativa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RecuperarIdSesionEstudiante", ReplyAction="http://tempuri.org/IService1/RecuperarIdSesionEstudianteResponse")]
        System.Threading.Tasks.Task<int> RecuperarIdSesionEstudianteAsync(string periodo, int numeroSesion, string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RecuperarProblematicas", ReplyAction="http://tempuri.org/IService1/RecuperarProblematicasResponse")]
        System.Threading.Tasks.Task<ServiceReference1.problematica[]> RecuperarProblematicasAsync(string periodo, string tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RecuperarProblematica", ReplyAction="http://tempuri.org/IService1/RecuperarProblematicaResponse")]
        System.Threading.Tasks.Task<ServiceReference1.problematicasesion> RecuperarProblematicaAsync(int idProblematica);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RecuperarEstudianteProblematica", ReplyAction="http://tempuri.org/IService1/RecuperarEstudianteProblematicaResponse")]
        System.Threading.Tasks.Task<ServiceReference1.estudiante> RecuperarEstudianteProblematicaAsync(int idProblematica);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RecuperaReporteGeneral", ReplyAction="http://tempuri.org/IService1/RecuperaReporteGeneralResponse")]
        System.Threading.Tasks.Task<ServiceReference1.reportegeneral> RecuperaReporteGeneralAsync(string periodoEscolar, int numeroSesion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RecuperarProblematicasReporte", ReplyAction="http://tempuri.org/IService1/RecuperarProblematicasReporteResponse")]
        System.Threading.Tasks.Task<string[]> RecuperarProblematicasReporteAsync(string periodoEscolar, int numeroSesion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RecuperarComentariosReporteGeneral", ReplyAction="http://tempuri.org/IService1/RecuperarComentariosReporteGeneralResponse")]
        System.Threading.Tasks.Task<string[]> RecuperarComentariosReporteGeneralAsync(string periodoEscolar, int numeroSesion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/recuperarPeriodosEscolares", ReplyAction="http://tempuri.org/IService1/recuperarPeriodosEscolaresResponse")]
        System.Threading.Tasks.Task<ServiceReference1.periodoescolar[]> recuperarPeriodosEscolaresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/recuperarTutorias", ReplyAction="http://tempuri.org/IService1/recuperarTutoriasResponse")]
        System.Threading.Tasks.Task<ServiceReference1.tutoria[]> recuperarTutoriasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/registrarFechasTutoria", ReplyAction="http://tempuri.org/IService1/registrarFechasTutoriaResponse")]
        System.Threading.Tasks.Task<bool> registrarFechasTutoriaAsync(int numeroSesion, System.DateTime fechaSesion, int numeroDias, System.DateTime fechaCierre, int idPeriodoEscolar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/modificarFechasTutoria", ReplyAction="http://tempuri.org/IService1/modificarFechasTutoriaResponse")]
        System.Threading.Tasks.Task<bool> modificarFechasTutoriaAsync(int idTutoria, System.DateTime fechaCierre, System.DateTime fechaSesion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/registrarHorarioSesionTutoria", ReplyAction="http://tempuri.org/IService1/registrarHorarioSesionTutoriaResponse")]
        System.Threading.Tasks.Task<bool> registrarHorarioSesionTutoriaAsync(int idEstudiante, int idTutoria, string horario, string lugar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/recuperarEstudiantes", ReplyAction="http://tempuri.org/IService1/recuperarEstudiantesResponse")]
        System.Threading.Tasks.Task<ServiceReference1.estudiante[]> recuperarEstudiantesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/recuperarEstudiantesTutor", ReplyAction="http://tempuri.org/IService1/recuperarEstudiantesTutorResponse")]
        System.Threading.Tasks.Task<ServiceReference1.estudiante[]> recuperarEstudiantesTutorAsync(int idTutor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/recuperarTutoriasPeriodo", ReplyAction="http://tempuri.org/IService1/recuperarTutoriasPeriodoResponse")]
        System.Threading.Tasks.Task<ServiceReference1.tutoria[]> recuperarTutoriasPeriodoAsync(int idPeriodo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/recuperarEstudiantesMatricula", ReplyAction="http://tempuri.org/IService1/recuperarEstudiantesMatriculaResponse")]
        System.Threading.Tasks.Task<ServiceReference1.estudiante[]> recuperarEstudiantesMatriculaAsync(string matricula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegistrarAcademico", ReplyAction="http://tempuri.org/IService1/RegistrarAcademicoResponse")]
        System.Threading.Tasks.Task<bool> RegistrarAcademicoAsync(ServiceReference1.academico academicoRegistro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuscarAcademico", ReplyAction="http://tempuri.org/IService1/BuscarAcademicoResponse")]
        System.Threading.Tasks.Task<bool> BuscarAcademicoAsync(int numeroEmpleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegistrarEstudiante", ReplyAction="http://tempuri.org/IService1/RegistrarEstudianteResponse")]
        System.Threading.Tasks.Task<bool> RegistrarEstudianteAsync(ServiceReference1.estudiante estudianteRegistro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegistrarExperienciaEducativa", ReplyAction="http://tempuri.org/IService1/RegistrarExperienciaEducativaResponse")]
        System.Threading.Tasks.Task<bool> RegistrarExperienciaEducativaAsync(ServiceReference1.experienciaeducativa experienciaeducativa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerAcademicos", ReplyAction="http://tempuri.org/IService1/ObtenerAcademicosResponse")]
        System.Threading.Tasks.Task<ServiceReference1.academico[]> ObtenerAcademicosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ObtenerEstudiantes", ReplyAction="http://tempuri.org/IService1/ObtenerEstudiantesResponse")]
        System.Threading.Tasks.Task<ServiceReference1.estudiante[]> ObtenerEstudiantesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuscarEstudiante", ReplyAction="http://tempuri.org/IService1/BuscarEstudianteResponse")]
        System.Threading.Tasks.Task<bool> BuscarEstudianteAsync(string matricula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RecuperarEstudiante", ReplyAction="http://tempuri.org/IService1/RecuperarEstudianteResponse")]
        System.Threading.Tasks.Task<ServiceReference1.estudiante> RecuperarEstudianteAsync(string matricula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RecuperarAcademico", ReplyAction="http://tempuri.org/IService1/RecuperarAcademicoResponse")]
        System.Threading.Tasks.Task<ServiceReference1.academico> RecuperarAcademicoAsync(int numeroempleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuscarExperienciaEducativa", ReplyAction="http://tempuri.org/IService1/BuscarExperienciaEducativaResponse")]
        System.Threading.Tasks.Task<bool> BuscarExperienciaEducativaAsync(int nrc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegistrarProgramaEducativo", ReplyAction="http://tempuri.org/IService1/RegistrarProgramaEducativoResponse")]
        System.Threading.Tasks.Task<bool> RegistrarProgramaEducativoAsync(string nombre, string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BuscarProgramaEducativo", ReplyAction="http://tempuri.org/IService1/BuscarProgramaEducativoResponse")]
        System.Threading.Tasks.Task<bool> BuscarProgramaEducativoAsync(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarEstudiante", ReplyAction="http://tempuri.org/IService1/ActualizarEstudianteResponse")]
        System.Threading.Tasks.Task<bool> ActualizarEstudianteAsync(string matricula, int tutor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/recuperarPeriodosEscolaresId", ReplyAction="http://tempuri.org/IService1/recuperarPeriodosEscolaresIdResponse")]
        System.Threading.Tasks.Task<ServiceReference1.periodoescolar> recuperarPeriodosEscolaresIdAsync(int idPeriodo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IService1Channel : ServiceReference1.IService1, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ServiceReference1.IService1>, ServiceReference1.IService1
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Service1Client() : 
                base(Service1Client.GetDefaultBinding(), Service1Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService1.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), Service1Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.academico> IniciarSesionAsync(int numeroEmpleado, string password)
        {
            return base.Channel.IniciarSesionAsync(numeroEmpleado, password);
        }
        
        public System.Threading.Tasks.Task<bool> EsTutorAsync(int numeroEmpleado)
        {
            return base.Channel.EsTutorAsync(numeroEmpleado);
        }
        
        public System.Threading.Tasks.Task<bool> EsJefeCarreraAsync(int numeroEmpleado)
        {
            return base.Channel.EsJefeCarreraAsync(numeroEmpleado);
        }
        
        public System.Threading.Tasks.Task<bool> EsCoordinadorAsync(int numeroEmpleado)
        {
            return base.Channel.EsCoordinadorAsync(numeroEmpleado);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.estudiante[]> RecuperarEstudiantesSesionAsync(int idTutor, int numeroSesion, string periodoEscolar)
        {
            return base.Channel.RecuperarEstudiantesSesionAsync(idTutor, numeroSesion, periodoEscolar);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrarReporteSesionAsync(ServiceReference1.sesion Sesion, string nombre, string periodo, int numeroSesion)
        {
            return base.Channel.RegistrarReporteSesionAsync(Sesion, nombre, periodo, numeroSesion);
        }
        
        public System.Threading.Tasks.Task<int> RecuperarIdSesionAsync(string periodo, int numeroSesion)
        {
            return base.Channel.RecuperarIdSesionAsync(periodo, numeroSesion);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.reportetutoria> CalcularPorcentajesReporteAsync(int idTutoria, int idTutor)
        {
            return base.Channel.CalcularPorcentajesReporteAsync(idTutoria, idTutor);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrarPorcentajesReporteAsync(int idtutoria, int idtutor, double porcentajeriesgo, double porcentajeasistencia)
        {
            return base.Channel.RegistrarPorcentajesReporteAsync(idtutoria, idtutor, porcentajeriesgo, porcentajeasistencia);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrarComentariosGeneralesAsync(int idTutoria, int idTutor, string comentariosGenerales)
        {
            return base.Channel.RegistrarComentariosGeneralesAsync(idTutoria, idTutor, comentariosGenerales);
        }
        
        public System.Threading.Tasks.Task<string[]> RecuperarInformacionExperienciasEducativasAsync()
        {
            return base.Channel.RecuperarInformacionExperienciasEducativasAsync();
        }
        
        public System.Threading.Tasks.Task<int> RegistrarProblematicaAsync(string tipo, string nombre)
        {
            return base.Channel.RegistrarProblematicaAsync(tipo, nombre);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrarProblematicaSesionAsync(int idProblematica, int idSesion, string descripcion, string experienciaEducativa)
        {
            return base.Channel.RegistrarProblematicaSesionAsync(idProblematica, idSesion, descripcion, experienciaEducativa);
        }
        
        public System.Threading.Tasks.Task<int> RecuperarIdSesionEstudianteAsync(string periodo, int numeroSesion, string nombre)
        {
            return base.Channel.RecuperarIdSesionEstudianteAsync(periodo, numeroSesion, nombre);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.problematica[]> RecuperarProblematicasAsync(string periodo, string tipo)
        {
            return base.Channel.RecuperarProblematicasAsync(periodo, tipo);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.problematicasesion> RecuperarProblematicaAsync(int idProblematica)
        {
            return base.Channel.RecuperarProblematicaAsync(idProblematica);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.estudiante> RecuperarEstudianteProblematicaAsync(int idProblematica)
        {
            return base.Channel.RecuperarEstudianteProblematicaAsync(idProblematica);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.reportegeneral> RecuperaReporteGeneralAsync(string periodoEscolar, int numeroSesion)
        {
            return base.Channel.RecuperaReporteGeneralAsync(periodoEscolar, numeroSesion);
        }
        
        public System.Threading.Tasks.Task<string[]> RecuperarProblematicasReporteAsync(string periodoEscolar, int numeroSesion)
        {
            return base.Channel.RecuperarProblematicasReporteAsync(periodoEscolar, numeroSesion);
        }
        
        public System.Threading.Tasks.Task<string[]> RecuperarComentariosReporteGeneralAsync(string periodoEscolar, int numeroSesion)
        {
            return base.Channel.RecuperarComentariosReporteGeneralAsync(periodoEscolar, numeroSesion);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.periodoescolar[]> recuperarPeriodosEscolaresAsync()
        {
            return base.Channel.recuperarPeriodosEscolaresAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.tutoria[]> recuperarTutoriasAsync()
        {
            return base.Channel.recuperarTutoriasAsync();
        }
        
        public System.Threading.Tasks.Task<bool> registrarFechasTutoriaAsync(int numeroSesion, System.DateTime fechaSesion, int numeroDias, System.DateTime fechaCierre, int idPeriodoEscolar)
        {
            return base.Channel.registrarFechasTutoriaAsync(numeroSesion, fechaSesion, numeroDias, fechaCierre, idPeriodoEscolar);
        }
        
        public System.Threading.Tasks.Task<bool> modificarFechasTutoriaAsync(int idTutoria, System.DateTime fechaCierre, System.DateTime fechaSesion)
        {
            return base.Channel.modificarFechasTutoriaAsync(idTutoria, fechaCierre, fechaSesion);
        }
        
        public System.Threading.Tasks.Task<bool> registrarHorarioSesionTutoriaAsync(int idEstudiante, int idTutoria, string horario, string lugar)
        {
            return base.Channel.registrarHorarioSesionTutoriaAsync(idEstudiante, idTutoria, horario, lugar);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.estudiante[]> recuperarEstudiantesAsync()
        {
            return base.Channel.recuperarEstudiantesAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.estudiante[]> recuperarEstudiantesTutorAsync(int idTutor)
        {
            return base.Channel.recuperarEstudiantesTutorAsync(idTutor);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.tutoria[]> recuperarTutoriasPeriodoAsync(int idPeriodo)
        {
            return base.Channel.recuperarTutoriasPeriodoAsync(idPeriodo);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.estudiante[]> recuperarEstudiantesMatriculaAsync(string matricula)
        {
            return base.Channel.recuperarEstudiantesMatriculaAsync(matricula);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrarAcademicoAsync(ServiceReference1.academico academicoRegistro)
        {
            return base.Channel.RegistrarAcademicoAsync(academicoRegistro);
        }
        
        public System.Threading.Tasks.Task<bool> BuscarAcademicoAsync(int numeroEmpleado)
        {
            return base.Channel.BuscarAcademicoAsync(numeroEmpleado);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrarEstudianteAsync(ServiceReference1.estudiante estudianteRegistro)
        {
            return base.Channel.RegistrarEstudianteAsync(estudianteRegistro);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrarExperienciaEducativaAsync(ServiceReference1.experienciaeducativa experienciaeducativa)
        {
            return base.Channel.RegistrarExperienciaEducativaAsync(experienciaeducativa);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.academico[]> ObtenerAcademicosAsync()
        {
            return base.Channel.ObtenerAcademicosAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.estudiante[]> ObtenerEstudiantesAsync()
        {
            return base.Channel.ObtenerEstudiantesAsync();
        }
        
        public System.Threading.Tasks.Task<bool> BuscarEstudianteAsync(string matricula)
        {
            return base.Channel.BuscarEstudianteAsync(matricula);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.estudiante> RecuperarEstudianteAsync(string matricula)
        {
            return base.Channel.RecuperarEstudianteAsync(matricula);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.academico> RecuperarAcademicoAsync(int numeroempleado)
        {
            return base.Channel.RecuperarAcademicoAsync(numeroempleado);
        }
        
        public System.Threading.Tasks.Task<bool> BuscarExperienciaEducativaAsync(int nrc)
        {
            return base.Channel.BuscarExperienciaEducativaAsync(nrc);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrarProgramaEducativoAsync(string nombre, string codigo)
        {
            return base.Channel.RegistrarProgramaEducativoAsync(nombre, codigo);
        }
        
        public System.Threading.Tasks.Task<bool> BuscarProgramaEducativoAsync(string codigo)
        {
            return base.Channel.BuscarProgramaEducativoAsync(codigo);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarEstudianteAsync(string matricula, int tutor)
        {
            return base.Channel.ActualizarEstudianteAsync(matricula, tutor);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.periodoescolar> recuperarPeriodosEscolaresIdAsync(int idPeriodo)
        {
            return base.Channel.recuperarPeriodosEscolaresIdAsync(idPeriodo);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:50369/Service1.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return Service1Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return Service1Client.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IService1,
        }
    }
}
